---
- name: Install Clickhouse
  hosts: clickhouse
  become_method: ansible.builtin.su
  roles:
    - clickhouse
- name: Install Vector
  hosts: vector
  become_method: ansible.builtin.su
  roles:
    - vector
- name: Install lighthouse
  hosts: lighthouse
  become_method: ansible.builtin.su
  handlers:
    - name: Nginx reload
      become: true
      ansible.builtin.service:
        name: nginx
        state: restarted
  pre_tasks:
    - name: Install git
      become: true
      ansible.builtin.apt:
        name: git
        state: present
        update_cache: true
    - name: Install nginx
      become: true
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true
    - name: Apply nginx config
      become: true
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: "0644"
  roles:
    - lighthouse
  post_tasks:
    - name: Lighthouse | Apply config
      become: true
      ansible.builtin.template:
        src: lighthouse_nginx.conf.j2
        dest: /etc/nginx/conf.d/lighthouse.conf
        mode: "0644"
        notify: Nginx reload
