- name: Install Vector
  hosts: vector
  become: true
  handlers:
    - name: Start vector service
      ansible.builtin.service:
        name: vector.service
        state: restarted
  tasks:
    - name: Create a vector directory if it does not exist
      ansible.builtin.file:
        path: /opt/vector
        state: directory
    - name: Create a data vector directory if it does not exist
      ansible.builtin.file:
        path: /var/lib/vector
        state: directory
    - name: Get vector distrib
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
        dest: "/tmp/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
    - name: Unarchive a file with extra options
      ansible.builtin.unarchive:
        src: /tmp/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz
        dest: /opt/vector
        extra_opts:
        - --strip-components=2
    - name: cd folder vector
      ansible.builtin.command: cd /opt/vector
      changed_when: false
    - name: Template Example
      template:
        src: vector.yaml.j2
        dest: /etc/vector/vector.yaml
    - name: install Vector into Systemd, run
      ansible.builtin.shell: bash "cp -av etc/systemd/vector.service /etc/systemd/system"
      notify: Start vector service
